import "./globals.css";
import Nav from "./components/Nav";
import Bot from "./components/Bot";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import Providers from "./components/Providers";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await getServerSession(authOptions);

	//console.log(session);

	return (
		<html lang="en">
			<Providers>
				<body
					suppressHydrationWarning={true}
					className=" flex flex-col items-center">
					<div className=" flex flex-col items-center max-w-8xl">
						<Nav
							user={session?.user}
							expires={session?.expires as string}
						/>
						{children}

						<Bot
							user={session?.user}
							expires={session?.expires as string}
						/>
					</div>
				</body>
			</Providers>
		</html>
	);
}
